# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1414011631);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1418731351);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1418730872);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1414010687);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 348160);
user_pref("browser.download.dir", "/home/stephen/Dropbox/employment/research-residencies/mozfest_2014/dev/shadow-puppetry/tmpdata");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140608211457");
user_pref("browser.showQuitWarning", true);
user_pref("browser.slowStartup.averageTime", 1224);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("browser.tabs.loadDivertedInBackground", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"webrtc-status-button\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"social-share-button\",\"action-button--jid1-f9uj2thwoam5gqjetpack-lightbeam_idget\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\",\"tabs-closebutton\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"action-button--jid1-f9uj2thwoam5gqjetpack-lightbeam_idget\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"newElementCount\":0}");
user_pref("browser.warnOnQuit", false);
user_pref("datareporting.healthreport.lastDataSubmissionFailureTime", "1414011782086");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1418730812106");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1418730861102");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1418817261102");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1414010629661");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1414010649543");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-info-bar-dismissed");
user_pref("datareporting.policy.firstRunTime", "1413840685017");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 885);
user_pref("datareporting.sessions.current.main", 21);
user_pref("datareporting.sessions.current.sessionRestored", 1081);
user_pref("datareporting.sessions.current.startTime", "1418731230089");
user_pref("datareporting.sessions.current.totalTime", 181);
user_pref("datareporting.sessions.currentIndex", 45);
user_pref("datareporting.sessions.previous.43", "{\"s\":1418730750217,\"a\":5,\"t\":180,\"c\":true,\"m\":90,\"fp\":1124,\"sr\":1266}");
user_pref("datareporting.sessions.previous.44", "{\"s\":1418730984157,\"a\":5,\"t\":30,\"c\":false,\"m\":20,\"fp\":1365,\"sr\":1520}");
user_pref("datareporting.sessions.prunedIndex", 42);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"jid1-F9UJ2thwoAm5gQ@jetpack\":{\"version\":\"1.0.10.2\",\"type\":\"extension\",\"descriptor\":\"/home/stephen/Dropbox/employment/research-residencies/mozfest_2014/data_shadow_puppetry/firefox_profiles/shadow_puppetry/extensions/jid1-F9UJ2thwoAm5gQ@jetpack.xpi\"},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"30.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"30.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "mint-search-enhancer%40linuxmint.com:1.0,%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D:1.0.7,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:30.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1406417690000,\"rdfTime\":1402263466000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1402264734000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1402264735000},\"mint-search-enhancer@linuxmint.com\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/mint-search-enhancer@linuxmint.com\",\"mtime\":1385484249000,\"rdfTime\":1336764609000},\"{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}\",\"mtime\":1385484250000,\"rdfTime\":1336770080000}}},{\"name\":\"app-profile\",\"addons\":{\"jid1-F9UJ2thwoAm5gQ@jetpack\":{\"descriptor\":\"/home/stephen/Dropbox/employment/research-residencies/mozfest_2014/data_shadow_puppetry/firefox_profiles/shadow_puppetry/extensions/jid1-F9UJ2thwoAm5gQ@jetpack.xpi\",\"mtime\":1413844542000}}}]");
user_pref("extensions.lastAppVersion", "30.0");
user_pref("extensions.lastPlatformVersion", "30.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", false);
user_pref("gecko.buildID", "20140608211457");
user_pref("gecko.mstone", "30.0");
user_pref("general.warnOnAboutConfig", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.database", "{\"files\":[{\"fingerprint\":\"7694f9704a4f2c416cb2f037286438\",\"exists\":true,\"page\":1,\"zoom\":\"auto\",\"scrollLeft\":-74,\"scrollTop\":792},{\"fingerprint\":\"5bf38abcfcfc641976131aff9fdc4d\",\"exists\":true,\"page\":1,\"zoom\":\"auto\",\"scrollLeft\":-74,\"scrollTop\":792},{\"fingerprint\":\"8210766ea6604075afccadef478686eb\",\"exists\":true,\"page\":1,\"zoom\":\"auto\",\"scrollLeft\":-82,\"scrollTop\":842}]}");
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1418730835);
user_pref("places.history.expiration.transient_current_max_pages", 66717);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1418731230);
user_pref("toolkit.telemetry.previousBuildID", "20140608211457");
